language: go
go:
- 1.10.x
script:
- make
install:
- go get -u golang.org/x/lint/golint
- go get golang.org/x/tools/cmd/goimports
env:
  global:
  - |
    RUNSCOPE_INTEGRATION_DESC="Slack: #test1 channel, send message on all test runs"
  - secure: M0bcxxYW2YX8FkqlkYlVyTxk9PS5TVKQ2uY59iAi1yIwybv4wShuRrUnc13LH3kg+/mf29kIUcnPT6ohYYdAMVMZbRFoQiF43gFrDjm8jU4Ow1kFOfb0G+JBWw8dYD5tNRgb4Ge++Z/GkagobuPfGYTgh+RzCuzWgHuG1JZMEv0CVtFALhLGd4WmzXPHFa+trE61cQLE7o6G1JJZBa2VurQrJOwFfJXj+R9fDaB7eKVQAvIPrFobsQpA36OHHTRmFKyqOj1HBGPssAvaOPux+m96WGYkdvr/+j3DaIr0SCyZUHb2cr/WgTudCHd1aJtfc90du1jihCYL02UGROKp9dW2c6tR+0Y/ce3//gub/M3z+6yKaVlLMnQmirOuWmPsWTRPRIE4NLIx8fCvgP1riFfARVnCNV1M3ndjUxcTHN8cS8yScq+DM8tLdWJ5hWCLCGVkCtSWK0/4Ck1MSYl8KgYW6cX7yNDiXnWkWPskXnfSQ4nWPzSwyc+a/W5Xs4Kz0c/Cz2ar2p6vEksWruq+BYP6JPec1/uznPk618yz6+c3OVQS29IFY0hg8DZIIjxTc5P1+CwbROiZ0CSxYOqFcCtSNsVn6s6W5JrjflM7+tyyjKlCfEJSOJWmvQy/EytnpAtuabu7E2XnFoVExxEZovBQw07upWhL7CYe1xSBz14=
  - secure: nKMIwRN9FAEjPm2j2gFIIS9QzhqfdfbrPolyOtjqQV/XRzbwkeDOT9o0KhOzKrAc6B5H7lxKW7WFOHGHHe/jEpaY8O+2S99uOdyWQDQvu37PiUtHIX/OkcSg2kYf7frwvvxDVAf+XKesbWtU4hwT/9Zam4Cv1ExSV/pMdSLsybL3py/b8hRfK4IOjTJ6ujLkJC54fb9sHkGZqa+PZ2mXfXRd7vJv9MCJaK9/CnD7vCPK8z7YSGjo22aD9WO+wfBaCVTOkrhLugHP/jDMfkDTRLwPSk0mG7tpz5UMEWM13LPeWRgXIybkLf60xVqgE3VnWW7apXCqdW4CdQ8I0KIx0C09LjwsNZdqOgJG7vfVT8o9oz6BpWvU2ERXWCIR9Awp9xAZdqJ9zVGOJWc4HgyCTpOaqRO647YD9NE5HtOB4iIhPqpPO4wBstcam/nXxTkTnQj12reLWW1UAPSr3QN+ZlMMhtemQfFz520zVDVEwhmK25JxsapkD8OkJ833FtqwUhrZz1KhUMu0Ah7BOoMr9FTpBNrkgaKVMETNAb9oDJp4bPJEoXX92KLdMwn4LPzzNJbclkLfQNxdB1SLeczsm3boBAehMM9IIN7xoAuYEv/Uo5Xlq3p2nAzx4VSixitOe1P6OeqbL5wtbDrQ7XYxC80kK7ciDmP7sHM/5uQlXrg=
