language: go
go:
- 1.10.x
script:
- make
after_success:
- make release
install:
- go get -u golang.org/x/lint/golint
- go get golang.org/x/tools/cmd/goimports
env:
  global:
  - |
    RUNSCOPE_INTEGRATION_DESC="Slack: #test1 channel, send message on all test runs"
  - DEBUG=1
  - TF_LOG=DEBUG
  - TF_ACC=1
  - secure: WuBIDsitJiSSj43a+sz4R9cDY2AF2ODerVkx2eKxXIXtKRLqjBxiQD8gekfTIprbiMfsOCMPr5cjp1AmjuZCWu10DrshAbPvTP6h5Fvm10CRkpdojyOoJZuRrhhZwpaahxo2tE53iLHXtQ+5CMKOecG1Z2ts7b3jWny93AVwuD+Jmft27KqBcFPceOL9mQgdMEBOTjTV5wdhKrRtiyzrVUx50odkuKXGKGFT8GdKyvF6KxuOA2TK+2o7tFiswEUXTWZUNM6weC84Mx/74VSy0tzy6+fTaDkYR5X4BcXQNthctLeElpw/bSqGWJZcEmLOBnPwbB5Si56f/jS5COdQ0bXmuQD+eE16vI+F5ufXHibP4Uh8ltLMEkj5YD6PWNL4A5xAnOps4zLBM43wxtRl00d9BmSn30VlY8TfTQALSR5CC/zB6ciNQm+Or9Awgolucj7MDA/dgreEElDRS2j/Gl9JlJ3DuKUWwEHn9KU3g4bYnnRqUSVWVjoPg+jOkkUWC+hb8N7KF89VUV+J7LvsfMJM5b3030WPIGug2GLc1avVrWGHPTgTXit6/HueLSuHdeD/nQOqBTarzAHdNP72ACcbcuaknAUUdo9nTZQUVCbjca8PkBveIosQP07RHBtoxixkgkNSLialZx2Uhlgu2MWbp8r1GEBauJMxLu4voBY=
  - secure: Om90Aveg0wYEu4SAdsjOWHrumvV7tIVCENelnGEPBQY9Fx3kFfPJEqLC1AnzRNITjwB0aRzFPAqoaAiEj1zIxxPdYC+H9XKbD48We+jBeHv8v/hgrKbeaZZqUzTqS5YYYZGV9gHosB9cGkdBhlHvfMPzw8M/l+j6OEbicPNGfuO8Q1OkNmFPI5oM4vO8seXbf6NXko3wXY/pMMtUssUKAzUfFZLUNv5T6VpHIpdT5YzkAPoGpto22joW1cTADni3xToaA90meN4DqBKYarrzxvqiLYsjl1SWV3D0Uk+zxjeu7smfROo8zkyratPPvUQu6x/MvjuwDrupaLJi9ffnW7utIJQuSJ1W5Au6aQYuZr16VJ9k9myns6lfkrvP2y1CIUgbUKV+JiScL0OOiCBI2sa7ipuzjtE6HbmPMqYb7wx4XsqSn7qLlvkg1Nn99UCU75WAxK95K62ZLqFmcqG5AMIqwU8LKpvCAv+wwiUW7Cw9p1X2hwTC+UxpUBJN8k6SonRmULh9h84LSpoCxA1g2bD1fuJvX3Oe74MmK1rHYZM0FXJM7W48wrD1fwR7IHtUh/5//3yeIRIFIg8YAYCKxr7MpGEBcG2HrILEmbzDydOUR9zG20BVFVXMqKRWyFITcJvScP8cHnrEOXFObZxCwrxIXxEltrc+x2XKxAmkzEg=
  - secure: F0uWRxBhl+W9AH4VvhQ8LGoE9xj4mx/sqr2I3CQ6ao6edG94JcjTeBtU5pz83X14NusRDBA4u92nGlCK/zJOryAgSbkH+KEACtaEWR2jn1CmPh33K7RGN/EMbqcQkvE+K0E3atTaphj2yt4sQn5oAsrFoxf0Z6Rls9YR9BC8WI9D5kjS/gPwRykA+THdpx976LOTW6JJEqn4dSdigp6ulvzN4fh8lPTPEvLMkDaLOwmfhgdFOGqtkxIg1CdBsI9HPOWwdT2p9LuZzG8Pad3axCQUABwo54IsQBw6vT1kIyMol/JNdxf4HhvzifomvFFY/OogzCdOFlvpRcTkX91meT0BXC9+PBicKuQspj6fI5HjxY9XWjYtkzMqWtA67kN11Dexv07HfVR8U/On3fHhtLkdzb1uhHQ3Tx3OfjrkiOQzg6YhPAO1SIiYswmft70sruSsXDo7hlOzBc5MH8TeWuWNPA7W9FoZMONCZyADTsNrDT3BCM/NgOjATdbveJMhuyvxRxqeeFdwaGZtJEsHISsZThX5e/gA+s3f4NiQ9a8rIuTIjfoCChFAkwJckYtF9jhppOVj9UvQ1+0HUXr0snJA0W8mjZLQZ0j8EHMKPu0OwYl+BCrLacgGNAgK+P0xPmYO00eyTxB/eLqq2+S4C3y33uaMkg2cd5v6lIMgaso=
